
# The default images for all our servers
IMAGE_NAME = "bento/ubuntu-22.04"

# Setting Host IP address => Don't forget to change the IP address in local.conf file
IP_HOST = "10.0.0.10"


Vagrant.configure("2") do |config|
  # Use the bento/ubuntu-20.04 box
  config.vm.box = IMAGE_NAME

  # Forward ports for OpenStack services
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 6080, host: 6080
  config.vm.network "forwarded_port", guest: 5000, host: 5001
  config.vm.network "forwarded_port", guest: 8774, host: 8774
  config.vm.network "forwarded_port", guest: 9696, host: 9696

  # Configure this IP address for the VM
  config.vm.network "private_network", ip: IP_HOST
  
    # Configure VM settings
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "12288"
      vb.cpus = 6
    end
  
    # Run shell provisioning script to install OpenStack (DevStack)
    config.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y git
    
      # add user stack and give him sudo power
      sudo useradd -s /bin/bash -d /opt/stack -m stack
      sudo chmod +x /opt/stack
      echo "stack ALL=(ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/stack
      
  
      # Clone DevStack repository
      sudo su - stack << EOF
      
      git clone https://opendev.org/openstack/devstack
  
      # Change to DevStack directory & create log directory
      cd devstack
      mkdir /opt/stack/logs/
  
      # Create a simple local.conf file for DevStack
      
      echo "[[local|localrc]]
      HOST_IP=10.0.0.10
      ADMIN_PASSWORD=secret
      DATABASE_PASSWORD=secret
      RABBIT_PASSWORD=secret
      SERVICE_PASSWORD=secret" > local.conf
  
      # Run DevStack installation
      ./stack.sh
      EOF
    SHELL
  end
